name: Run Cypress Tests

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 5 * * 1" # Scheduled to run every Monday at 5:00 AM UTC

jobs:
  test:
    name: Run Cypress Tests on Node.js ${{ matrix.node_version }} and ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        node_version: ['18.x'] # Test on Node.js version 18.x
        os: [ubuntu-20.04] # Test on Ubuntu 20.04

    container:
      image: cypress/browsers:22.12.0 # Cypress Docker image with pre-installed browsers
      options: --user 1001

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Step 2: Install dependencies
      - name: Install Dependencies
        run: npm install

      # Step 3: Run Cypress tests
      - name: Run Cypress Tests
        uses: cypress-io/github-action@v5
        with:
          browser: chrome
          spec: cypress/e2e/PageWeb/*.cy.js # Update this path to match your test files
          record: true
          parallel: true # Runs test in parallel using settings above
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Step 4: Upload artifacts for debugging purposes
      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: cypress-artifacts
          path: |
            cypress/screenshots/
            cypress/videos/