name: Run Cypress Tests

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 5 * * 1" # Scheduled to run every Monday at 5:00 AM UTC

jobs:
  test:
    name: Run Cypress Tests on Node.js ${{ matrix.node_version }} and ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        # Run 3 copies of the current job in parallel
        containers: [1, 2, 3]
        node_version: ['18.x'] # Test on Node.js version 18.x
        os: [ubuntu-20.04] # Test on Ubuntu 20.04

    container:
      image: cypress/browsers:22.12.0 # Cypress Docker image with pre-installed browsers
      options: --user 1001

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Step 2: Set up Node.js environment
      - name: Setup Node.js ${{ matrix.node_version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node_version }}

      # Step 3: Install dependencies
      - name: Install Dependencies
        run: npm install

      # Step 4: Run Cypress tests
      - name: Run Cypress Tests
        uses: cypress-io/github-action@v5
        with:
          browser: chrome
          spec: cypress/e2e/PageWeb/*.cy.js # Update this path to match your test files

      # Step 5: Collect artifacts (screenshots and videos)
      - name: Collect Artifacts
        run: |
          mkdir -p artifacts
          if [ -d "cypress/screenshots" ]; then
            cp -r cypress/screenshots artifacts/
          else
            echo "No screenshots directory found."
          fi
          if [ -d "cypress/videos" ]; then
            cp -r cypress/videos artifacts/
          else
            echo "No videos directory found."
          fi

      # Step 6: Upload artifacts for debugging purposes
      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: cypress-artifacts
          path: artifacts