name: Run Cypress Tests

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 5 * * 1" # Scheduled to run every Monday at 5:00 AM UTC

jobs:
  test:
    name: Run Cypress Tests on Node.js ${{ matrix.node_version }} and ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        node_version: ['18.x'] # Test on Node.js version 18.x
        os: [ubuntu-20.04] # Test on Ubuntu 20.04

    steps:
      # Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Setup Node.js environment
      - name: Setup Node.js ${{ matrix.node_version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node_version }}

      # Install Cypress and other dependencies
      - name: Install Dependencies
        run: npm install

      # Run Cypress tests
      - name: Run Cypress Tests
        uses: cypress-io/github-action@v5
        with:
          browser: chrome
          spec: cypress/e2e/PageWeb/*.cy.js # Update if tests reside in a subfolder

      # Collect artifacts (screenshots and videos)
      - name: Collect Artifacts
        run: |
          mkdir -p artifacts
          if [ -d "cypress/screenshots" ]; then
            cp -r cypress/screenshots artifacts/
          else
            echo "No screenshots directory found."
          fi
          if [ -d "cypress/videos" ]; then
            cp -r cypress/videos artifacts/
          else
            echo "No videos directory found."
          fi

      # Upload artifacts for debugging purposes
      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: cypress-artifacts
          path: artifacts